
dashboardPage( 
  dashboardHeader(title = "Company Analysis"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("About",tabName = "about", icon = icon("dollar-sign")),
      menuItem("Price",tabName = "price", icon = icon("chart-line")),
      menuItem("Cumulative Return",tabName = "return", icon = icon("chart-line")),
      menuItem("Quarterly Income Statement",tabName = "qis", icon = icon("file-invoice-dollar")),
      menuItem("Quarterly Balance Sheet",tabName = "qbs", icon = icon("file-invoice-dollar")),
      menuItem("Quarterly Cash Flow Statement",tabName = "qcf", icon = icon("file-invoice-dollar")),
      menuItem("Quarterly Metrics",tabName = "qm", icon = icon("search-dollar")),
      menuItem("Annual Income Statement",tabName = "ais", icon = icon("file-invoice-dollar")),
      menuItem("Annual Balance Sheet",tabName = "abs", icon = icon("file-invoice-dollar")),
      menuItem("Annual Cash Flow Statement",tabName = "acf", icon = icon("file-invoice-dollar")),
      menuItem("Annual Metrics",tabName = "am", icon = icon("search-dollar")),
      menuItem("Industry Metrics",tabName = "industry", icon = icon("search-dollar"))
    )
  ),
  
  dashboardBody(
    tabItems(
      tabItem(tabName = "about",
              fluidRow(
                column(12,
                       h2('Interactive Database for Public Company Financials'),
                       box("I built this application in order to better visualize company financials and metrics over time.You will be able to see quarterly and annual data since the company's inception as well as the cumulative return of a dollar invested since inception. After assessing the company's fundamentals,it will be interesting to compare industry metrics and see how whether your company is undervaluedor overvalued, underachieving or overachieving in certain metrics.", width = 12)
                       ))
      ),
      tabItem(tabName = "price",
              fluidRow(column(12,
                              h3('Market Price Summary'),
                              selectizeInput("ticker",
                                             label = 'Company Ticker',
                                             choices = unique(pricedf$ticker),
                                             multiple = T, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       ),
              fluidRow(column(12, textOutput('acquired'), style = 'color:red')
                       ),
              fluidRow(box(dygraphOutput('price'), width = 12)
                       ),
              fluidRow(box(h4('Company Description'),
                           h5(textOutput('industry')),
                           textOutput('description'), width = 12)
                      )
      ),
      tabItem(tabName = "return",
              fluidRow(column(12,
                              h3('$1 Invested Since Inception'),
                              selectizeInput("cumticker",
                                             label = 'Company Ticker',
                                             choices = unique(cumdf$ticker),
                                             multiple = T, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL"))
                       ),
              fluidRow(box(dygraphOutput('cumprice'), width = 12)
                       )
      ),
      tabItem(tabName = "qis",
              fluidRow(column(6,
                              h3('Quarterly Income Statement Items'),
                              selectizeInput("qisticker",
                                             label = 'Company Ticker',
                                             choices = unique(quarterbs$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("qisitem",
                                             label = 'Line Item',
                                             choices = colnames(quarteris)[c(-1,-8,-9,-10)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select an item'),
                                             selected = "revenue")),
                       box(plotlyOutput("quarteris"), width = 12))
      ),
      tabItem(tabName = "qbs",
              fluidRow(column(6,
                              h3('Quarterly Balance Sheet Items'),
                              selectizeInput("qbsticker",
                                             label = 'Company Ticker',
                                             choices = unique(quarterbs$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("qbsitem",
                                             label = 'Line Item',
                                             choices = colnames(quarterbs)[c(-1,-12,-13,-14)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select an item'),
                                             selected = "assets")),
                       box(plotlyOutput("quarterbs"), width = 12))
      ),
      tabItem(tabName = "qcf",
              fluidRow(column(6,
                              h3('Quarterly Cash Flow Items'),
                              selectizeInput("qcfticker",
                                             label = 'Company Ticker',
                                             choices = unique(quartercf$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("qcfitem",
                                             label = 'Line Item',
                                             choices = colnames(quartercf)[c(-1,-8,-9,-10)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select an item'),
                                             selected = "cash.from.operating.activities")),
                       box(plotlyOutput("quartercf"),  width = 12))
      ),
      tabItem(tabName = "qm",
              fluidRow(column(6,
                              h3('Quarterly Metrics'),
                              selectizeInput("qmticker",
                                             label = 'Company Ticker',
                                             choices = unique(quartermetrics$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("qmitem",
                                             label = 'Quarterly Metrics',
                                             choices = colnames(quartermetrics)[c(-1,-19,-20)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a metric'),
                                             selected = "roe")),
                       box(plotlyOutput("quartermetrics"), width = 12))
      ),
      tabItem(tabName = "ais",
              fluidRow(column(6,
                              h3('Annual Income Statement Items'),
                              selectizeInput("aisticker",
                                             label = 'Company Ticker',
                                             choices = unique(yearis$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("aisitem",
                                             label = 'Line Item',
                                             choices = colnames(yearis)[c(-1,-2,-3,-4)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select an item'),
                                             selected = "revenue")),
                       box(plotlyOutput("yearis"), width = 12))
      ),
      tabItem(tabName = "abs",
              fluidRow(column(6,
                              h3('Annual Balance Sheet Items'),
                              selectizeInput("absticker",
                                             label = 'Company Ticker',
                                             choices = unique(yearbs$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("absitem",
                                             label = 'Line Item',
                                             choices = colnames(yearbs)[c(-1,-2,-13,-14)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select an item'),
                                             selected = "assets")),
                       box(plotlyOutput("yearbs"), width = 12))
      ),
      tabItem(tabName = "acf",
              fluidRow(column(6,
                              h3('Annual Cash Flow Items'),
                              selectizeInput("acfticker",
                                             label = 'Company Ticker',
                                             choices = unique(yearcf$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("acfitem",
                                             label = 'Line Item',
                                             choices = colnames(yearcf)[c(-1,-2,-3,-4)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select an item'),
                                             selected = "cash.from.operating.activities")),
                       box(plotlyOutput("yearcf"), width = 12))
      ),
      tabItem(tabName = "am",
              fluidRow(column(6,
                              h3('Annual Metrics'),
                              selectizeInput("amticker",
                                             label = 'Company Ticker',
                                             choices = unique(yearmetrics$ticker),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a company'),
                                             selected = "AAPL")),
                       column(6,
                              br(),br(),br(),
                              selectizeInput("amitem",
                                             label = 'Annual Metrics',
                                             choices = colnames(yearmetrics)[c(-1,-2,-3,-4)],
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a metric'),
                                             selected = "roe")),
                       box(plotlyOutput("yearmetrics"), width = 12))
      ),
      tabItem(tabName = "industry",
              fluidRow(column(6,
                              h3('Industry Metric Comparison'),
                              selectizeInput("industrymetric",
                                             label = 'Industry Metric',
                                             choices = colnames(yearcoind[c(28:40,43,44,45,48,49,50)]),
                                             multiple = F, 
                                             options = list(maxItems = 1,placeholder = 'Select a metric'),
                                             selected = 'roe'))
              ),
              fluidRow(box(plotOutput('industryboxplot'), width = 12)
              ),
              fluidRow(column(12,
                              selectizeInput("industry",
                                             label = 'Industry',
                                             choices = unique(yearcoind$industry.y),
                                             multiple = T, 
                                             options = list(maxItems = 29,placeholder = 'Select an industry'),
                                             selected = unique(yearcoind$industry.y)))
              )

      )
    )
  )
)
